import Link from 'next/link';

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-gray-50 text-gray-800 font-sans">
      {/* Navigation */}
      <nav className="bg-white border-b border-gray-200 py-4 px-6">
        <div className="max-w-7xl mx-auto flex justify-between items-center">
          <Link href="/" className="text-2xl font-bold text-green-800 hover:text-green-700">
            EUshop
          </Link>
          <Link href="/" className="text-sm font-medium text-gray-600 hover:text-gray-900">
            Back to Home
          </Link>
        </div>
      </nav>

      {/* Main Content */}
      <main className="max-w-3xl mx-auto px-6 py-12 bg-white my-8 rounded-lg shadow-sm border border-gray-200">
        <h1 className="text-3xl font-extrabold text-gray-900 mb-6">Terms of Service</h1>
        <p className="text-sm text-gray-500 mb-8">Last Updated: July 2026</p>

        <section className="space-y-6">
          <div>
            <h2 className="text-xl font-bold text-gray-900 mb-2">1. Scope and Acceptance</h2>
            <p className="text-gray-700 leading-relaxed">
              Welcome to EUshop (the "Platform"). These Terms of Service ("Terms") govern your access to and use of our online marketplace. By creating an account or purchasing products on EUshop, you agree to comply with these Terms. The Platform facilitates transactions between independent sellers of specialty foods and consumer buyers located strictly within the European Union (EU) Single Market.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-bold text-gray-900 mb-2">2. Geographic and Delivery Constraints</h2>
            <p className="text-gray-700 leading-relaxed">
              EUshop is currently optimized only for trading and delivery within the EU Single Market. Due to complex customs and veterinary inspection requirements for cross-border transport of foodstuffs, shipments originating from or destined for non-EU territories (including Switzerland, the United Kingdom, and Norway) are not permitted on the Platform.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-bold text-gray-900 mb-2">3. Seller Verification and Compliance (DSA & DAC7)</h2>
            <p className="text-gray-700 leading-relaxed mb-3">
              To sell products on EUshop, commercial merchants must complete identity verification in compliance with Article 30 of the EU Digital Services Act (DSA) and DAC7 reporting rules.
            </p>
            <ul className="list-disc pl-6 space-y-2 text-gray-700">
              <li>Sellers must provide true and accurate information, including legal address, company register ID, VAT/tax IDs, and a self-certification of compliance with EU food safety standards.</li>
              <li>Under DAC7, transaction volumes and revenues generated by sellers will be reported to EU tax authorities annually.</li>
            </ul>
          </div>

          <div>
            <h2 className="text-xl font-bold text-gray-900 mb-2">4. Food Safety and Ingredient Labeling</h2>
            <p className="text-gray-700 leading-relaxed mb-3">
              Sellers are solely responsible for compliance with Regulation (EU) No 1169/2011 (Food Information to Consumers).
            </p>
            <ul className="list-disc pl-6 space-y-2 text-gray-700">
              <li>All listings must declare the presence of any of the 14 major allergens (such as nuts, gluten, dairy, or soy) and provide a complete list of ingredients before checkout.</li>
              <li>Perishable goods must be packaged and shipped using appropriate thermal/cold-chain packaging where required.</li>
            </ul>
          </div>

          <div>
            <h2 className="text-xl font-bold text-gray-900 mb-2">5. Payments and Marketplace Commission</h2>
            <p className="text-gray-700 leading-relaxed">
              Payment processing and payout split services are handled by Stripe Connect. By listing goods on the Platform, sellers agree to a marketplace commission (standard take-rate is 15%) deducted automatically from checkout totals before payout.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-bold text-gray-900 mb-2">6. Consumer Rights & 14-Day Right of Withdrawal</h2>
            <p className="text-gray-700 leading-relaxed">
              Under the EU Consumer Rights Directive, buyers generally have a 14-day right of withdrawal from distance purchases. However, <strong>this right of withdrawal does not apply to perishable goods</strong> (including fresh cheese, cured meats, or items with short shelf-lives) once shipped, nor does it apply to sealed goods opened by the consumer after delivery due to health protection and hygiene reasons.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-bold text-gray-900 mb-2">7. Disputes and Jurisdiction</h2>
            <p className="text-gray-700 leading-relaxed">
              Transactions occur directly between the buyer and the seller. EUshop is a facilitating platform and is not liable for product defects or shipping delays. These Terms are governed by the laws of the Czech Republic, and any disputes will be subject to the courts of Prague.
            </p>
          </div>
        </section>
      </main>

      {/* Footer */}
      <footer className="bg-gray-900 text-gray-300 py-8">
        <div className="max-w-7xl mx-auto px-4 text-center text-sm">
          <p>&copy; {new Date().getFullYear()} EUshop. All rights reserved.</p>
        </div>
      </footer>
    </div>
  );
}
