import Link from 'next/link';
import { PageWrapper } from '../components/layout/PageWrapper';

export default function TermsOfService() {
  return (
    <PageWrapper>
      <div className="max-w-4xl mx-auto py-6">
        <div className="bg-white dark:bg-gray-900 border border-gray-150 dark:border-gray-800 rounded-3xl p-8 sm:p-10 shadow-sm">
          <h1 className="text-3xl font-extrabold text-brand-dark dark:text-white mb-2 font-display">
            Terms of Service
          </h1>
          <p className="text-xs text-gray-400 dark:text-gray-500 mb-8">Last Updated: July 2026</p>

          <div className="prose prose-slate dark:prose-invert max-w-none space-y-6 text-sm text-gray-700 dark:text-gray-300 leading-relaxed">
            <section>
              <h2 className="text-xl font-bold text-brand-dark dark:text-white mb-2 font-display">
                1. Scope and Acceptance
              </h2>
              <p>
                Welcome to EUshop (the "Platform"). These Terms of Service ("Terms") govern your access to and use of our online marketplace. By creating an account or purchasing products on EUshop, you agree to comply with these Terms. The Platform facilitates transactions between independent sellers of specialty foods and consumer buyers located strictly within the European Union (EU) Single Market.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-brand-dark dark:text-white mb-2 font-display">
                2. Geographic and Delivery Constraints
              </h2>
              <p>
                EUshop is currently optimized only for trading and delivery within the EU Single Market. Due to complex customs and veterinary inspection requirements for cross-border transport of foodstuffs, shipments originating from or destined for non-EU territories (including Switzerland, the United Kingdom, and Norway) are not permitted on the Platform.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-brand-dark dark:text-white mb-2 font-display">
                3. Seller Verification and Compliance (DSA & DAC7)
              </h2>
              <p className="mb-3">
                To sell products on EUshop, commercial merchants must complete identity verification in compliance with Article 30 of the EU Digital Services Act (DSA) and DAC7 reporting rules.
              </p>
              <ul className="list-disc pl-6 space-y-2">
                <li>Sellers must provide true and accurate information, including legal address, company register ID, VAT/tax IDs, and a self-certification of compliance with EU food safety standards.</li>
                <li>Under DAC7, transaction volumes and revenues generated by sellers will be reported to EU tax authorities annually.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-bold text-brand-dark dark:text-white mb-2 font-display">
                4. Food Safety and Ingredient Labeling
              </h2>
              <p className="mb-3">
                Sellers are solely responsible for compliance with Regulation (EU) No 1169/2011 (Food Information to Consumers).
              </p>
              <ul className="list-disc pl-6 space-y-2">
                <li>All listings must declare the presence of any of the 14 major allergens (such as nuts, gluten, dairy, or soy) and provide a complete list of ingredients before checkout.</li>
                <li>Perishable goods must be packaged and shipped using appropriate thermal/cold-chain packaging where required.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-bold text-brand-dark dark:text-white mb-2 font-display">
                5. Payments and Marketplace Commission
              </h2>
              <p>
                Payment processing and payout split services are handled by Stripe Connect. By listing goods on the Platform, sellers agree to a marketplace commission (standard take-rate is 15%) deducted automatically from checkout totals before payout.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-brand-dark dark:text-white mb-2 font-display">
                6. Consumer Rights & 14-Day Right of Withdrawal
              </h2>
              <p>
                Under the EU Consumer Rights Directive, buyers generally have a 14-day right of withdrawal from distance purchases. However, <strong className="text-gray-950 dark:text-white">this right of withdrawal does not apply to perishable goods</strong> (including fresh cheese, cured meats, or items with short shelf-lives) once shipped, nor does it apply to sealed goods opened by the consumer after delivery due to health protection and hygiene reasons.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-brand-dark dark:text-white mb-2 font-display">
                7. Disputes and Jurisdiction
              </h2>
              <p>
                Transactions occur directly between the buyer and the seller. EUshop is a facilitating platform and is not liable for product defects or shipping delays. These Terms are governed by the laws of the Czech Republic, and any disputes will be subject to the courts of Prague.
              </p>
            </section>
          </div>
        </div>
      </div>
    </PageWrapper>
  );
}

